Repository DeveloperAcademy-POSTECH/MacC-Team10-Pivoters, pull requests merged in 2023-11, with the labels that each got.

#5 [Chore] SwintLint 적용
  .gitignore
  Projects/.swiftlint.yml
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/Dummy.swift
  Projects/App/Sources/MyApp.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: ⚙️ Chore

#8 [Feat] 프로젝트 데이터 모델 설계
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Team.swift
Labels: ✨ Feature

#10 [Feat] SwiftDataManager 구현
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
Labels: ✨ Feature

#12 [Feat] 선수 드래그해서 위치 옮기기
  Projects/Common/Resources/Assets.xcassets/Contents.json
  Projects/Common/Resources/Assets.xcassets/field.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/field.imageset/filed.png
  Projects/Common/Resources/Assets.xcassets/uniform.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/uniform.imageset/uniform.png
  Projects/Core/Sources/Extension/CGSize.swift
  Projects/Core/Sources/Models/OffsetValue.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Team.swift
  Projects/Feature/Sources/AppContentView.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/PlayerView.swift
Labels: ✨ Feature

#14 [Feat] 메인뷰 lo-fi UI 반영
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/MainView.swift
  Projects/App/Sources/MyApp.swift
Labels: ✨ Feature

#16 [Feat] 선수 포지션 이동에 대한 제약조건들
  Projects/Core/Sources/Extension/CGSize.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
Labels: ✨ Feature

#18 [Feat] ShareView 기반 이미지 반출 기능 구현
  Projects/App/Sources/MyApp.swift
  Projects/Common/Sources/Extension/CustomActivityViewController.swift
  Projects/Common/Sources/Extension/View+.swift
  Projects/Common/Sources/Helper/ImageMetadataProvider.swift
  Projects/Feature/Sources/MainView.swift
  Projects/Feature/Sources/ShareView.swift
Labels: ✨ Feature

#20 [Feat] 유니폼 커스텀 기능 구현
  Projects/App/Project.swift
  Projects/Common/Resources/Assets.xcassets/tempsvg.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/tempsvg.imageset/tempsvg.svg
  Projects/Common/Sources/Uniform.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/OverlapUniform.swift
  Projects/Feature/Sources/View/UniformView.swift
Labels: ✨ Feature

#22 [Feat] 반응형 모달 구현
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/TempMainView.swift
  Projects/Feature/Sources/View/UniformView.swift
Labels: ✨ Feature

#23 [Feat] 포메이션 템플릿 제공
  Projects/Core/Sources/Models/FormationType.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
Labels: ✨ Feature

#25 [Feat] 테마 뷰 구현
  Projects/Common/Project.swift
  Projects/Common/Resources/Assets.xcassets/themeBlackGreen.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/themeBlackGreen.imageset/themeBlackGreen.png
  Projects/Common/Resources/Assets.xcassets/themeBlueGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/themeBlueGray.imageset/themeBlueGray.png
  Projects/Common/Resources/Assets.xcassets/themeOrangeGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/themeOrangeGray.imageset/themeOrangeGray.png
  Projects/Common/Resources/Assets.xcassets/themeSkyGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/themeSkyGray.imageset/themeSkyGray.png
  Projects/Common/Sources/Theme.swift
  Projects/Common/Sources/Uniform.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/ThemeObservable.swift
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/ThemeView.swift
Labels: ✨ Feature

#31 [Feat] 팀 변경 기능 구현
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/TeamChangeModalView.swift
Labels: ✨ Feature

#32 Feature/#30
  Projects/Feature/Sources/View/LaunchScreenView.swift
  Projects/Feature/Sources/View/MainView.swift
Labels: ✨ Feature

#35 [Feat] 모달 위치에 따른 뷰 변경
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
Labels: ✈️ ASAP, ✨ Feature

#37 [Feat] 테마 - 경기장, 배경, 미리보기 반영
  Projects/Common/Resources/Assets.xcassets/backgroundBlack.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/backgroundBlack.imageset/backgroundBlack.png
  Projects/Common/Resources/Assets.xcassets/backgroundBlue.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/backgroundBlue.imageset/backgroundBlue.png
  Projects/Common/Resources/Assets.xcassets/backgroundGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/backgroundGray.imageset/backgroundGray.png
  Projects/Common/Resources/Assets.xcassets/backgroundWhite.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/backgroundWhite.imageset/backgroundWhite.png
  Projects/Common/Resources/Assets.xcassets/fieldBlack.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/fieldBlack.imageset/fieldBlack.png
  Projects/Common/Resources/Assets.xcassets/fieldBlue.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/fieldBlue.imageset/fieldBlue.png
  Projects/Common/Resources/Assets.xcassets/fieldGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/fieldGray.imageset/fieldGray.png
  Projects/Common/Resources/Assets.xcassets/fieldGreen.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/fieldGreen.imageset/fieldGreen.png
  Projects/Common/Resources/Assets.xcassets/previewBlackBlue.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/previewBlackBlue.imageset/previewBlackBlue.png
  Projects/Common/Resources/Assets.xcassets/previewBlueGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/previewBlueGray.imageset/previewBlueGray.png
  Projects/Common/Resources/Assets.xcassets/previewGrayBlack.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/previewGrayBlack.imageset/previewGrayBlack.png
  Projects/Common/Resources/Assets.xcassets/previewWhiteGreen.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/previewWhiteGreen.imageset/previewWhiteGreen.png
  Projects/Common/Resources/Assets.xcassets/themeBlackGreen.imageset/themeBlackGreen.png
  Projects/Common/Resources/Assets.xcassets/themeBlueGray.imageset/themeBlueGray.png
  Projects/Common/Resources/Assets.xcassets/themeOrangeGray.imageset/themeOrangeGray.png
  Projects/Common/Resources/Assets.xcassets/themeSkyGray.imageset/themeSkyGray.png
  Projects/Common/Sources/Theme.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/ThemeObservable.swift
  Projects/Feature/Sources/View/ThemeView.swift
Labels: ✨ Feature

#40 feat: 유니폼 기능 구현, 에셋 문제로 인해 중단(#38)
  Projects/Common/Resources/Assets.xcassets/plainBorder.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/plainBorder.imageset/plainLayer.svg
  Projects/Common/Resources/Assets.xcassets/plainPrimary.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/plainPrimary.imageset/plainPrimary.svg
  Projects/Common/Resources/Assets.xcassets/stripeBorder.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/stripeBorder.imageset/stripeBorder.svg
  Projects/Common/Resources/Assets.xcassets/stripePrimary.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/stripePrimary.imageset/stripePrimary.svg
  Projects/Common/Resources/Assets.xcassets/stripeSecondary.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/stripeSecondary.imageset/stripeSecondary.svg
  Projects/Common/Sources/Uniform.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/OverlapUniform.swift
  Projects/Feature/Sources/View/UniformView.swift
Labels: ✈️ ASAP, ✨ Feature

#41 [Feat] 디자인 시스템 적용 - 폰트, 컬러
  Projects/Common/Resources/Font/Pretendard-Black.otf
  Projects/Common/Resources/Font/Pretendard-Bold.otf
  Projects/Common/Resources/Font/Pretendard-ExtraBold.otf
  Projects/Common/Resources/Font/Pretendard-ExtraLight.otf
  Projects/Common/Resources/Font/Pretendard-Light.otf
  Projects/Common/Resources/Font/Pretendard-Medium.otf
  Projects/Common/Resources/Font/Pretendard-Regular.otf
  Projects/Common/Resources/Font/Pretendard-SemiBold.otf
  Projects/Common/Resources/Font/Pretendard-Thin.otf
  Projects/Common/Sources/DesignSystem/Color+.swift
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
Labels: ⚙️ Chore, ✨ Feature

#43 [Feat] 선수 추가 및 선택 기능 구현
  Projects/Common/Resources/Assets.xcassets/addButton.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/addButton.imageset/addButton.png
  Projects/Common/Resources/Assets.xcassets/cirecleUniform.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/cirecleUniform.imageset/cirecleUniform.png
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Core/Sources/Models/OffsetValue.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
  Projects/Feature/Sources/View/TempMainView.swift
Labels: ✨ Feature

#44 [Feat] 메인 to 편집뷰 트랜지션 UX 구현
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/View/Carousel.swift
  Projects/Feature/Sources/View/LaunchScreenView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/ShareView.swift
Labels: ✨ Feature

#46 [Feat] 테마 선택 후 뷰 반영 기능
  Projects/Common/Resources/Assets.xcassets/DarkGray.colorset/Contents.json
  Projects/Common/Resources/Assets.xcassets/field.imageset/Contents.json
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Common/Sources/Theme.swift
  Projects/Core/Sources/Models/FormationType.swift
  Projects/Feature/Sources/AppContentView.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/LaunchScreenView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerView.swift
  Projects/Feature/Sources/View/ShareView.swift
  Projects/Feature/Sources/View/ThemeView.swift
Labels: ✈️ ASAP, ✨ Feature

#52 [Feat] 팀 CRUD 기능 구현
  Projects/Common/Sources/DesignSystem/ViewModifier/TeamCellViewModifier.swift
  Projects/Common/Sources/Extension/View+.swift
  Projects/Feature/Sources/MockData.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/Observable/TeamSelectObservable.swift
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/TeamChangeModalView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCell.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCreateView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamSelectView.swift
Labels: ✨ Feature

#54 [Chore] TeamCRUDView Conflict 해결
  Projects/App/Sources/MyApp.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Core/Sources/Models/OffsetValue.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Team.swift
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/RefactoredTeamObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/View/TeamCRUDView.swift
Labels: ⚙️ Chore

#57 [Feat] 스쿼드 별로 테마, 라인업 커스텀 하는 기능
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/MockData.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/TeamManagementObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/Observable/ThemeObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
  Projects/Feature/Sources/View/TeamManagementView.swift
  Projects/Feature/Sources/View/TempMainView.swift
  Projects/Feature/Sources/View/ThemeView.swift
Labels: ✨ Feature

#58 [Refactor] 메인뷰 코드 개선
  Projects/App/Sources/MyApp.swift
  Projects/Feature/Sources/Observable/MainObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/View/Carousel.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
Labels: 🏃🏻 Refactoring

#60 [Feat] 팀 선택뷰 SwiftData 연결
  Projects/Core/Sources/Models/RefactoredTeam.swift
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
  Projects/Feature/Sources/Observable/RefactoredTeamObservable.swift
  Projects/Feature/Sources/Observable/TeamCreateObservable.swift
  Projects/Feature/Sources/Observable/TeamSelectObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/TeamCRUDView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCell.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCreateView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamSelectView.swift
Labels: ✈️ ASAP, ✨ Feature

#62 [Feat] 유니폼 기능 구현
  Projects/Common/Resources/Assets.xcassets/plainBorder.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/plainBorder.imageset/plainBorder.svg
  Projects/Common/Resources/Assets.xcassets/plainBorder.imageset/plainLayer.svg
  Projects/Common/Resources/Assets.xcassets/plainPrimary.imageset/plainPrimary.svg
  Projects/Common/Resources/Assets.xcassets/stripeBorder.imageset/stripeBorder.svg
  Projects/Common/Resources/Assets.xcassets/stripePrimary.imageset/stripePrimary.svg
  Projects/Common/Resources/Assets.xcassets/stripeSecondary.imageset/stripeSecondary.svg
  Projects/Feature/Sources/Observable/UniformObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/OverlapUniform.swift
  Projects/Feature/Sources/View/PlayerView.swift
  Projects/Feature/Sources/View/UniformView.swift
Labels: ✨ Feature

#63 [Chore] SwiftData Team - Lineup 모델 의존 해결
  Projects/Core/Sources/Models/RefactoredLineup.swift
  Projects/Core/Sources/Models/RefactoredTeam.swift
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
  Projects/Feature/Sources/View/LineupCRUDView.swift
  Projects/Feature/Sources/View/TeamCRUDView.swift
Labels: ⚙️ Chore

#65 [Feat] ShareImage 구현
  Projects/Common/Resources/Assets.xcassets/shareBlack.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/shareBlack.imageset/Square.png
  Projects/Common/Resources/Assets.xcassets/shareBlue.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/shareBlue.imageset/Square.png
  Projects/Common/Resources/Assets.xcassets/shareGray.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/shareGray.imageset/Square.png
  Projects/Common/Resources/Assets.xcassets/shareGreen.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/shareGreen.imageset/Square.png
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Common/Sources/Extension/View+.swift
  Projects/Common/Sources/Theme.swift
  Projects/Feature/Sources/Helper/ImageMetadataProvider.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ShareView.swift
Labels: ✨ Feature

#67 [Style] 디자인 디테일 반영
  Projects/Common/Resources/Assets.xcassets/addButton.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/addButton.imageset/addButton.png
  Projects/Common/Resources/Assets.xcassets/circleUniform.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/circleUniform.imageset/circleUniform.png
  Projects/Common/Resources/Assets.xcassets/cirecleUniform.imageset/cirecleUniform.png
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Feature/Sources/Observable/MainObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
  Projects/Feature/Sources/View/PlayerView.swift
  Projects/Feature/Sources/View/UniformView.swift
Labels: ✨ Feature

#68 [Feat] 데이터 SwiftData 연동
  Projects/App/Sources/MyApp.swift
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Core/Sources/Models/OffsetValue.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Team.swift
  Projects/Core/Sources/Models/TypeOfFormation.swift
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
  Projects/Core/Sources/SwiftData/TeamContainer.swift
  Projects/Feature/Sources/Helper/ImageMetadataProvider.swift
  Projects/Feature/Sources/MockData.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/TeamManagementObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/Observable/TeamSelect/TeamCreateObservable.swift
  Projects/Feature/Sources/Observable/TeamSelect/TeamSelectObservable.swift
  Projects/Feature/Sources/Observable/Temp/TempMainObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ShareView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCell.swift
  Projects/Feature/Sources/View/Temp/TempMainView.swift
  Projects/Feature/Sources/View/TempMainView.swift
Labels: ✈️ ASAP, ✨ Feature

#77 [Feat] 선수추가, 선택 SwiftData 연동
  Projects/Core/Sources/Models/Human.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/RefactoredLineup.swift
  Projects/Core/Sources/Models/Team.swift
  Projects/Core/Sources/SwiftData/SwiftDataManager.swift
  Projects/Core/Sources/SwiftData/TeamContainer.swift
  Projects/Feature/Sources/MockData.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/Observable/ThemeObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
  Projects/Feature/Sources/View/PlayerView.swift
Labels: ✨ Feature

#80 [Fix] ShareView 수정 요소 반영
  Projects/App/Project.swift
  Projects/Feature/Sources/View/ShareView.swift
Labels: ✨ Feature, 🛠️ Fix

#82 [Feat] 팀 변경 List, 팀 추가(팀명 / 스쿼드명 변경) UI 개선
  Projects/Common/Sources/DesignSystem/Color+.swift
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Feature/Sources/Observable/Edit/ChangeTeamInfoObservable.swift
  Projects/Feature/Sources/Observable/TeamSelect/TeamCreateObservable.swift
  Projects/Feature/Sources/Observable/TeamSelect/TeamSelectObservable.swift
  Projects/Feature/Sources/View/Edit/ChangeTeamInfoView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCell.swift
  Projects/Feature/Sources/View/TeamSelect/TeamCreateView.swift
  Projects/Feature/Sources/View/TeamSelect/TeamSelectView.swift
Labels: ✈️ ASAP, ✨ Feature

#84 [Feat] 스플래시 뷰, 아이콘, 앱 이름 적용
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/App/Resources/Assets.xcassets/appstore.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/appstore.imageset/appstore.png
  Projects/App/Resources/Assets.xcassets/playstore.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/playstore.imageset/playstore.png
  Projects/Common/Resources/Assets.xcassets/splash.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/splash.imageset/splash.png
  Projects/Common/Resources/Assets.xcassets/splashTitle.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/splashTitle.imageset/splashTitle.png
  Projects/Feature/Sources/View/LaunchScreenView.swift
Labels: ✈️ ASAP, ⚙️ Chore, ✨ Feature

#85 [Feat] 선수선택 기능 수정
  Projects/Common/Resources/Assets.xcassets/Color/Contents.json
  Projects/Common/Resources/Assets.xcassets/Color/DarkGray.colorset/Contents.json
  Projects/Common/Resources/Assets.xcassets/Color/TintColor.colorset/Contents.json
  Projects/Core/Sources/Models/Lineup.swift
  Projects/Feature/Sources/Observable/FieldObservable.swift
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/TeamObservable.swift
  Projects/Feature/Sources/Observable/Temp/ModalSegmentedObservable.swift
  Projects/Feature/Sources/Observable/ThemeObservable.swift
  Projects/Feature/Sources/View/FieldView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/ModalSegmentedView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
  Projects/Feature/Sources/View/PlayerView.swift
  Projects/Feature/Sources/View/ShareView.swift
Labels: ✨ Feature

#88 [Feat] 선수선택 뷰 수정
  Projects/App/Resources/Localizable.xcstrings
  Projects/Feature/Sources/Observable/PlayerSelectionObservable.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/PlayerSelectionView.swift
Labels: ✨ Feature

#91 [Release] 앱스토어 1.0.0 배포 전 최종 QA
  Projects/App/Resources/Dummy.swift
  Projects/App/Resources/Localizable.xcstrings
  Projects/App/Sources/MyApp.swift
  Projects/Common/Sources/DesignSystem/Theme+.swift
  Projects/Common/Sources/DesignSystem/Uniform+.swift
  Projects/Common/Sources/Dummy.swift
  Projects/Feature/Sources/AppContentView.swift
  Projects/Feature/Sources/Dummy.swift
  Projects/Feature/Sources/MockData.swift
  Projects/Feature/Sources/Observable/Edit/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/Edit/ThemeObservable.swift
  Projects/Feature/Sources/Observable/Main/FieldObservable.swift
  Projects/Feature/Sources/Observable/Main/MainObservable.swift
  Projects/Feature/Sources/Observable/Main/TeamObservable.swift
  Projects/Feature/Sources/Observable/PlayerObservable.swift
  Projects/Feature/Sources/Observable/Temp/RefactoredTeamObservable.swift
  Projects/Feature/Sources/View/Edit/ChangeTeamInfoView.swift
  Projects/Feature/Sources/View/Edit/ModalSegmentedView.swift
  Projects/Feature/Sources/View/Edit/Player/PlayerView.swift
  Projects/Feature/Sources/View/Edit/PlayerSelectionView.swift
  Projects/Feature/Sources/View/Edit/ShareView.swift
  Projects/Feature/Sources/View/Edit/TeamManagementView.swift
  Projects/Feature/Sources/View/Edit/ThemeView.swift
  Projects/Feature/Sources/View/LaunchScreen/LaunchScreenView.swift
  Projects/Feature/Sources/View/Main/Carousel.swift
  Projects/Feature/Sources/View/Main/FieldView.swift
  Projects/Feature/Sources/View/Main/MainView.swift
  Projects/Feature/Sources/View/Temp/LineupCRUDView.swift
  Projects/Feature/Sources/View/Temp/TeamCRUDView.swift
Labels: ⚙️ Chore, 🍎 Release

#93 [Release] v1.0.1 업데이트
  Projects/App/Project.swift
  Projects/Feature/Sources/Observable/Main/MainObservable.swift
  Projects/Feature/Sources/View/Edit/ModalSegmentedView.swift
  Projects/Feature/Sources/View/Main/Carousel.swift
  Projects/Feature/Sources/View/Main/FieldView.swift
  Projects/Feature/Sources/View/Main/MainView.swift
Labels: ⚙️ Chore, 🍎 Release

#96 [Release] v1.0.2 배포
  Projects/App/Project.swift
  Projects/Feature/Sources/View/LaunchScreen/LaunchScreenView.swift
Labels: ⚙️ Chore, 🍎 Release

#105 [Feat] v1.1.0 수정 요소 반영
  Projects/App/Project.swift
  Projects/App/Resources/Localizable.xcstrings
  Projects/Core/Sources/Models/Formation.swift
  Projects/Feature/Sources/Observable/Edit/TeamManagementObservable.swift
  Projects/Feature/Sources/Observable/Main/FieldObservable.swift
  Projects/Feature/Sources/View/Edit/ModalSegmentedView.swift
  Projects/Feature/Sources/View/Edit/TeamManagementView.swift
  Projects/Feature/Sources/View/Main/FieldView.swift
  Projects/Feature/Sources/View/Main/MainView.swift
Labels: ✨ Feature
