Repository DeveloperAcademy-POSTECH/MacC-Team10-Pivoters, pull requests merged in 2023-12, with the labels that each got.

#108 [Feat] 선수 선택 뷰 리디자인 및 기능 개선
  Projects/App/Resources/Localizable.xcstrings
  Projects/Common/Resources/Assets.xcassets/addButton.imageset/addButton.png
  Projects/Common/Resources/Assets.xcassets/clickedPlayerButton.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/clickedPlayerButton.imageset/clickedPlayerButton.png
  Projects/Common/Resources/Assets.xcassets/emptyUniform.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/emptyUniform.imageset/emptyUniform.png
  Projects/Common/Resources/Assets.xcassets/playerAddButton.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/playerAddButton.imageset/playerAddButton.png
  Projects/Common/Resources/Assets.xcassets/playerButton.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/playerButton.imageset/playerButton.png
  Projects/Common/Resources/Assets.xcassets/selectedEmptyUniform.imageset/Contents.json
  Projects/Common/Resources/Assets.xcassets/selectedEmptyUniform.imageset/selectedEmptyUniform.png
  Projects/Feature/Sources/Observable/Edit/AddPlayerObservable.swift
  Projects/Feature/Sources/Observable/Edit/PlayerSelectionObservable.swift
  Projects/Feature/Sources/Observable/Edit/TeamManagementObservable.swift
  Projects/Feature/Sources/Observable/Main/MainObservable.swift
  Projects/Feature/Sources/View/Edit/AddPlayerView.swift
  Projects/Feature/Sources/View/Edit/Player/PlayerView.swift
  Projects/Feature/Sources/View/Edit/PlayerSelectionView.swift
  Projects/Feature/Sources/View/Main/FieldView.swift
  Projects/Feature/Sources/View/Main/MainView.swift
Labels: ✨ Feature

#109 [Feat] 모달 UX 개선
  Projects/Common/Sources/DesignSystem/CGFloat+.swift
  Projects/Common/Sources/DesignSystem/Font+.swift
  Projects/Common/Sources/DesignSystem/ViewModifier/SheetModifier.swift
  Projects/Common/Sources/Extension/View+.swift
  Projects/Feature/Sources/Observable/Main/FieldObservable.swift
  Projects/Feature/Sources/Observable/Main/MainObservable.swift
  Projects/Feature/Sources/View/Edit/ChangeTeamInfoView.swift
  Projects/Feature/Sources/View/Edit/ModalSegmentedView.swift
  Projects/Feature/Sources/View/Edit/ShareView.swift
  Projects/Feature/Sources/View/Edit/TeamManagementView.swift
  Projects/Feature/Sources/View/LaunchScreen/LaunchScreenView.swift
  Projects/Feature/Sources/View/Main/Carousel.swift
  Projects/Feature/Sources/View/Main/MainView.swift
Labels: ✈️ ASAP, ⚙️ Chore, ✨ Feature

#111 [Bug] 선수편집 기능 버그 픽스
  Projects/Feature/Sources/Observable/Edit/PlayerSelectionObservable.swift
  Projects/Feature/Sources/View/Edit/PlayerSelectionView.swift
Labels: ✈️ ASAP, 🐜 Bug, ✨ Feature

#120 [Bug] 선수 추가 모달 자동으로 내려가는 현상 해결
  Projects/Core/Sources/SwiftData/TeamContainer.swift
  Projects/Feature/Sources/View/Edit/AddPlayerView.swift
  Projects/Feature/Sources/View/Edit/PlayerSelectionView.swift
  Projects/Feature/Sources/View/Temp/TeamCRUDView.swift
Labels: ✈️ ASAP, 🐜 Bug
